-- CONSTRUÇÃO
SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [ITENS NOTAS FISCAIS]

SELECT * FROM [NOTAS FISCAIS]
-- JUNTA 2 TABELAS
SELECT * FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO 
--PEGA 3 COLUNAS DA CONSULTA ANTERIOR E REMOVE O VALOR DIA DA DATA
--								VARCHAR DA DATA NO ESTILO 120, SUBSTRING PEGANDO DA LINHA 1 ATÉ 7
SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES
, INF.QUANTIDADE  FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO 

--FAZ A SOMA DOS VALORES DE COMPRA DE CADA CLIENTE PARA CADA MES DO ANO
SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES
--SOMA DAS COMPRAS DE CADA CLIENTE
, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES  FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO 
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7)
ORDER BY CPF, ANO_MES
-- MOSTRA NOME E LIMITE DE COMPRA PARA CADA CLIENTE
SELECT TC.NOME, TC.[VOLUME DE COMPRA] FROM [TABELA DE CLIENTES] TC

SELECT * FROM [TABELA DE CLIENTES] TC
-- JUNTA AS TABELAS
SELECT TC.NOME, CQ.ANO_MES, CQ.QUANTIDADE_MES, TC.[VOLUME DE COMPRA]
FROM
(SELECT NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7) AS ANO_MES
, SUM(INF.QUANTIDADE) AS QUANTIDADE_MES  FROM [NOTAS FISCAIS] NF
INNER JOIN [ITENS NOTAS FISCAIS] INF
ON NF.NUMERO = INF.NUMERO 
GROUP BY NF.CPF, SUBSTRING(CONVERT(VARCHAR, NF.[DATA], 120),1,7)) CQ
INNER JOIN [TABELA DE CLIENTES] TC ON TC.CPF = CQ.CPF
--RESULTADO:  
-- VERIFICAR SE AS VENDAS POR MES FORAM INVALIDAS COM BASE NO LIMITE DE VENDAS

SELECT X.NOME, X.MES_ANO, X.QUANTIDADE,
CASE WHEN Y.[VOLUME DE COMPRA]  < X.QUANTIDADE THEN 'VENDA INVALIDA'
WHEN Y.[VOLUME DE COMPRA] >= X.QUANTIDADE  THEN 'VENDA VALIDA'
ELSE 'PRODUTO BARATO' END AS STATUS_VENDA
 FROM (
SELECT A.CPF, A.NOME, SUBSTRING(CONVERT(VARCHAR,  B.DATA, 120),1,7) AS MES_ANO , 
SUM(C.QUANTIDADE) AS QUANTIDADE FROM 
[TABELA DE CLIENTES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF
INNER JOIN [ITENS NOTAS FISCAIS] C
ON B.NUMERO = C.NUMERO
GROUP BY A.CPF, A.NOME, SUBSTRING(CONVERT(VARCHAR,  B.DATA, 120),1,7)
) X INNER JOIN [TABELA DE CLIENTES] Y ON X.CPF = Y.CPF
ORDER BY X.NOME, X.MES_ANO

-- MOSTRA APENAS AS VENDAS INVALIDAS, COM A QUANTIDADE VENDIDA E O LIMITE DO CLIENTE
SELECT N.NOME, N.MES_ANO, TC.[VOLUME DE COMPRA], N.QUANTIDADE, CONVERT(DECIMAL(15,2), ( (N.QUANTIDADE/TC.[VOLUME DE COMPRA]) - 1) * 100)  AS VARIACAO, N.STATUS_VENDA FROM
(SELECT X.NOME, X.MES_ANO, X.QUANTIDADE,
CASE WHEN Y.[VOLUME DE COMPRA]  < X.QUANTIDADE THEN 'VENDA INVALIDA'
WHEN Y.[VOLUME DE COMPRA] >= X.QUANTIDADE  THEN 'VENDA VALIDA'
ELSE 'PRODUTO BARATO' END AS STATUS_VENDA
 FROM (
SELECT A.CPF, A.NOME, SUBSTRING(CONVERT(VARCHAR,  B.DATA, 120),1,7) AS MES_ANO , 
SUM(C.QUANTIDADE) AS QUANTIDADE FROM 
[TABELA DE CLIENTES] A
INNER JOIN [NOTAS FISCAIS] B
ON A.CPF = B.CPF
INNER JOIN [ITENS NOTAS FISCAIS] C
ON B.NUMERO = C.NUMERO
GROUP BY A.CPF, A.NOME, SUBSTRING(CONVERT(VARCHAR,  B.DATA, 120),1,7)
) X INNER JOIN [TABELA DE CLIENTES] Y ON X.CPF = Y.CPF) N
INNER JOIN [TABELA DE CLIENTES] TC ON TC.NOME = N.NOME
WHERE STATUS_VENDA = 'VENDA INVALIDA'
ORDER BY NOME, MES_ANO