--Criando Function para gerar numeros aleatorios



--- VALOR MINIMO SEJA 100
--- VALOR MAXIMO SEJA 500
-- ROUND NAO PODE SER CHAMADO DENTRO DE UMA FUNCAO
SELECT ROUND(((500 - 100 - 1) * RAND() + 100), 0)
--CRIANDO VIEW COM O VALOR DE ROUND
CREATE VIEW VW_ALEATORIO AS SELECT RAND() AS VALUE
--GERA VALOR ALEATORIO
SELECT * FROM VW_ALEATORIO
--OR ALTER
CREATE FUNCTION NumeroAleatorio(@VAL_INIC INT, @VAL_FINAL INT) RETURNS INT
AS
BEGIN
DECLARE @ALEATORIO INT
DECLARE @ALEATORIO_FLOAT FLOAT
--CRIA VARIAVEL PARA RECEBER VALOR DA VIEW ALEATORIO
SELECT @ALEATORIO_FLOAT = VALUE FROM VW_ALEATORIO
SET @ALEATORIO = ROUND(((@VAL_FINAL - @VAL_INIC) * @ALEATORIO_FLOAT + @VAL_INIC), 0)
RETURN @ALEATORIO
END
-- GERA UM NUMERO ALEATORIO ENTRE X E Y
SELECT [dbo].[NumeroAleatorio](0,1000)
--		//				//				//				//				//			
-- Inserindo valores aleatorios em uma tabela com primary key
DECLARE @TABELA TABLE (NUMERO INT UNIQUE)
DECLARE @CONTADOR INT
DECLARE @CONTMAXIMO INT
SET @CONTADOR = 1
SET @CONTMAXIMO = 100
WHILE @CONTADOR <= @CONTMAXIMO
BEGIN
	BEGIN TRY
		INSERT INTO @TABELA (NUMERO) VALUES 
			([dbo].[NumeroAleatorio](0,1000))
		SET @CONTADOR += 1
	END TRY
	BEGIN CATCH
	PRINT('ERRO')
	END CATCH
END
SELECT * FROM @TABELA ORDER BY 1

--		//				//				//				//				//			
