--Criando Function para gerar numeros aleatorios



--- VALOR MINIMO SEJA 100
--- VALOR MAXIMO SEJA 500
-- ROUND NAO PODE SER CHAMADO DENTRO DE UMA FUNCAO
SELECT ROUND(((500 - 100 - 1) * RAND() + 100), 0)
--CRIANDO VIEW COM O VALOR DE ROUND
CREATE VIEW VW_ALEATORIO AS SELECT RAND() AS VALUE
--GERA VALOR ALEATORIO
SELECT * FROM VW_ALEATORIO
--OR ALTER
CREATE FUNCTION NumeroAleatorio(@VAL_INIC INT, @VAL_FINAL INT) RETURNS INT
AS
BEGIN
DECLARE @ALEATORIO INT
DECLARE @ALEATORIO_FLOAT FLOAT
--CRIA VARIAVEL PARA RECEBER VALOR DA VIEW ALEATORIO
SELECT @ALEATORIO_FLOAT = VALUE FROM VW_ALEATORIO
SET @ALEATORIO = ROUND(((@VAL_FINAL - @VAL_INIC) * @ALEATORIO_FLOAT + @VAL_INIC), 0)
RETURN @ALEATORIO
END
-- GERA UM NUMERO ALEATORIO ENTRE X E Y
SELECT [dbo].[NumeroAleatorio](0,1000)


