
--Variaveis só são validas durante a execução
DECLARE @MATRICULA VARCHAR(5), @NOME VARCHAR(100), @PERCENTUAL FLOAT, @DATA DATE, @FERIAS BIT
DECLARE @BAIRRO VARCHAR(100)
-- DECLARAÇÃO SIMPLES
SET @MATRICULA = '00240'
SET @NOME = 'Cláudia Rodrigues'
SET @PERCENTUAL = 0.10
SET @DATA = '20120312'
SET @FERIAS = 1
SET @BAIRRO = 'Jardins'

INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO]
, [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES
(@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO)

SELECT * FROM [TABELA DE VENDEDORES]

DECLARE @NUMNOTAS INT
--DECLARAÇÃO COM CONSULTA
SELECT @NUMNOTAS = COUNT(*) FROM [NOTAS FISCAIS]
    WHERE DATA = '20170101'
PRINT @NUMNOTAS

--PASSA NOME DO OBJETO(VARCHAR) E TIPO (U = TABELA)
IF OBJECT_ID('TABELA_TESTE', 'U') IS NOT NULL DROP TABLE TABELA_TESTE
IF OBJECT_ID('TABELA_TESTE', 'U') IS NULL CREATE TABLE TABELA_TESTE (ID VARCHAR(10))

--VERIFICA SE É MEIO OU FIM DE SEMANA
DECLARE @DIA_SEMANA VARCHAR(20)
DECLARE @NUMERO_DIAS INT
SET @NUMERO_DIAS = 9
SET @DIA_SEMANA = DATENAME(WEEKDAY, DATEADD(DAY, @NUMERO_DIAS, GETDATE()))
PRINT @DIA_SEMANA
IF @DIA_SEMANA = 'Domingo' OR @DIA_SEMANA = 'Sábado'
   PRINT 'Este dia é fim de semana'
ELSE
   PRINT 'Este dia é dia da semana'

--VERIFICA A QUANTIDADE DE NOTAS
   DECLARE @DATANOTA DATE
DECLARE @NUMNOTAS INT
SET @DATANOTA = '20170102'
SELECT @NUMNOTAS = COUNT(*)
FROM [NOTAS FISCAIS] 
WHERE DATA = @DATANOTA
IF @NUMNOTAS > 70
    PRINT 'Muita nota'
ELSE
    PRINT 'Pouca nota'
PRINT @NUMNOTAS

--VERIFICA SE O LIMITE DE CREDITO DO BAIRRO "ÁGUA SANTA" FOI ULTRAPASSADO
DECLARE @LIMITE_MAXIMO FLOAT, @LIMITE_ATUAL FLOAT
DECLARE @BAIRRO2 VARCHAR(20)

SET @BAIRRO = 'Água Santa'
SET @LIMITE_MAXIMO = 50000
SELECT @LIMITE_ATUAL = SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO
IF @LIMITE_MAXIMO <= (SELECT SUM([LIMITE DE CREDITO]) FROM [TABELA DE CLIENTES] WHERE BAIRRO = @BAIRRO2)
BEGIN
   PRINT 'Valor estourou. Não é possível abrir novos créditos'
END
ELSE
BEGIN
   PRINT 'Valor não estourou. É possível abrir novos créditos'
END

