SELECT * FROM [TABELA DE PRODUTOS]

UPDATE [TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 5
WHERE [CODIGO DO PRODUTO] = '1040107'

UPDATE [TABELA DE PRODUTOS] SET [SABOR] = 'Laranja', [EMBALAGEM] = 'PET'
WHERE [CODIGO DO PRODUTO] = '1040107'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga'

UPDATE [TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = [PREÇO DE LISTA] * 1.10
WHERE [SABOR] = 'Manga'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga'

--update from
--PREÇO = 7
SELECT * FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1000889'
--PREÇO = 6.309
SELECT * FROM HELLO_WORLD_01.DBO.PRODUTOS
WHERE PRODUTOS.CÓDIGO = '1000889'

--MOSTRA OS 2 PREÇOS
SELECT A.[CÓDIGO], A.[PREÇO LISTA], B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA]
FROM HELLO_WORLD_01.DBO.PRODUTOS A INNER JOIN [TABELA DE PRODUTOS] B
ON A.CÓDIGO = B.[CODIGO DO PRODUTO]
WHERE A.CÓDIGO = '1000889'
-- PASSA O VALOR DA TABELA B PARA A TABELA A
UPDATE A SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA]
FROM  HELLO_WORLD_01.DBO.PRODUTOS A INNER JOIN [TABELA DE PRODUTOS] B
ON A.CÓDIGO = B.[CODIGO DO PRODUTO]
WHERE A.CÓDIGO = '1000889'