--BD SUCOS_VENDAS
SELECT * FROM [TABELA DE PRODUTOS]

UPDATE [TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 5
WHERE [CODIGO DO PRODUTO] = '1040107'

UPDATE [TABELA DE PRODUTOS] SET [SABOR] = 'Laranja', [EMBALAGEM] = 'PET'
WHERE [CODIGO DO PRODUTO] = '1040107'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga'

UPDATE [TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = [PREÇO DE LISTA] * 1.10
WHERE [SABOR] = 'Manga'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [SABOR] = 'Manga'

--update from
--PREÇO = 7
SELECT * FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = '1000889'
--PREÇO = 6.309
SELECT * FROM HELLO_WORLD_01.DBO.PRODUTOS
WHERE PRODUTOS.CÓDIGO = '1000889'

--MOSTRA OS 2 PREÇOS
SELECT A.[CÓDIGO], A.[PREÇO LISTA], B.[CODIGO DO PRODUTO], B.[PREÇO DE LISTA]
FROM HELLO_WORLD_01.DBO.PRODUTOS A INNER JOIN [TABELA DE PRODUTOS] B
ON A.CÓDIGO = B.[CODIGO DO PRODUTO]
WHERE A.CÓDIGO = '1000889'
-- PASSA O VALOR DA TABELA B PARA A TABELA A
UPDATE A SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA]
FROM  HELLO_WORLD_01.DBO.PRODUTOS A INNER JOIN [TABELA DE PRODUTOS] B
ON A.CÓDIGO = B.[CODIGO DO PRODUTO]
WHERE A.CÓDIGO = '1000889'

--AUMENTA EM 30% O VOLUME DE COMPRA DOS CLIENTES QUE TEM OS MESMOS BAIRROS QUE OS VENDEDORES
UPDATE HELLO_WORLD_01.DBO.CLIENTES SET [VOLUME DE COMPRA] = [VOLUME DE COMPRA] * 1.3
FROM HELLO_WORLD_01.DBO.[CLIENTES] A
INNER JOIN HELLO_WORLD_01.DBO.[VENDEDORES] B
ON A.[BAIRRO] = B.[BAIRRO]

-- MERGE TEM A MESMA FUNÇÃO MAS A SINTAXE MUDA:    BD HELLO_WORLD
UPDATE [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] SET [PREÇO DE LISTA] = 8
WHERE [CODIGO DO PRODUTO] = '1002334'

MERGE INTO [PRODUTOS] A
USING [SUCOS_VENDAS].[DBO].[TABELA DE PRODUTOS] B
ON A.[CÓDIGO] = B.[CODIGO DO PRODUTO]
AND A.[CÓDIGO] = '1002334'
WHEN MATCHED THEN
UPDATE SET A.[PREÇO LISTA] = B.[PREÇO DE LISTA];