
SELECT * FROM [VENDEDORES]

BEGIN TRANSACTION

UPDATE [VENDEDORES] SET [COMISSAO] = [COMISSAO] * 1.15

INSERT INTO [VENDEDORES] ([MATRÕCULA], [NOME], [BAIRRO],[COMISS√O], [DATA ADMISS√O], [F…RIAS])
VALUES ('99999','Joao da Silva','IcaraÅE,0.08,'2014-09-01',0)

ROLLBACK

COMMIT

